language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- pytest
env:
  global:
  - secure: Q1qSZ8mtg8QCeJ0A7v5H1N+4kBqnrfRFuMpIP/do8PcqkcFzQ1kj+YPs2mMTfYn1HZeiFC5cYHYXMowjqkPcjpZeVlKOKaHEnFvqp4hUHwX/5O9rxe0tVk3Ye4ap/U8UcohXBtUIt66uq9zF6w82/P3CiAdsuJr73KTjTLTx1Wsr+NbzKGYyCL9l2bQzfXbmgvYAo2gO0WNJwSBc96v23RGEI6k5tPRrPs8R+BrV+rEV6Uhss3KZniRojYEApq7mb/TMOgIXv4fs1oWqABZrmAVfrs5/TGxBlte/Opfqe1dJJd9TmMWbMQkJspoaxb7EEM8FmCcKhyyM8heui7ndSjQE/WfJRL3UKb95/SP2j5vx/VKv/lszSuuapW9Je4DUn9+lXg+yShDxmkjDd5/5vFrGIqRZ3PbAJbI8RYY+AuCVWNKx6M61UIU5Ykgx0xcJE2mHoKW54jYZzJkhGSY5IEQd+14eixUQ7mubI+Y6g9QIwiIYgs8qnhZRjzcmaoraq22YQZafcWz9Sfkg72QKxfWuYd6x/PVjUcaPb6HHL9KtqhIzEsfjEBRXjj0XOkaRTLeEOAoW3ilWqKdKBmQUxL7kxjbKUSKJt+g01rctY5Rk2wAfEvO8g39Nglj6C9o+dwfcbLn5KabQCTEjgDQDUMUBTY79U05K/bHmTr8mmGE=
deploy:
  provider: heroku
  buildpack: python
  strategy: git
  api_key:
    secure: S7rju2g8LOpCG3YMIZhk72SD3j55WZGPRYontZHuWrqG44/okjwKCFTQwNpQyvfDLYxdNwxyRNit+B2GslifwnAqqT87vBBRzMvVkdMm1KsCXZTZGiIkXzimAKztctBvMWMCKJzswSFyhUbEEiQCuHU6Uq5eXZyK4r2ju3c/t+9osAtRoG1Ld7UuZKEUU85lDIKbYKp1JVcKA3uouGAQyHa7MoSiUiH+2gcPw9DzdUK9e8CUo+qWtYgi1+fDh5tLjlMW5Jl2W7rkQkApzytfRI8+V+Tjw9VzmCCnL7zJoWB3Y4y8zqeXLaexa+3yUymNOISugqT9F9FuE6Yja0DPXKIGzsxKa5AxiR0WwYP+TeTq6w02dIUObleek5NK26L2/gSsEuMIRjIfWifWGCT+oOGkhRVJg/8RrSGq2hJHG3WpOFShOAQX4f4xUhYBGJCIXXvQXpUvI0DSXavIjV0b3xqfKmIa14ZiEu64qlodmrW4Cqudgm4xoQyY6QSMfNKZe742zWUc7UdzAtov2pjaKorrCJ7lGLXE4Mp2TRkCYeavJ8mJtv0WFdpZO08bTopktTcH2eG73u952YthctEku9Cwc5dt/iaP4yCopHABue/rxIn+ySN7ntpTeKd21zAV5ITU6GKW5pWBybCskPOb6sleKZAumbHlFDe2fdfiQwE=
  app: scrpr-develop
  on:
    repo: IgorBolotnikov/SCRPR
    branch: develop
  run:
    - "python manage.py syncdb --noinput"
    - "python manage.py migrate --all"
    - restart
