language: python
python:
- '3.8'
# install:
# - pip install -r requirements.txt
# script:
# - pytest
# after_success:
# - coveralls
# deploy:
#   provider: heroku
#   api_key:
#     secure: p1FiTP9nzbImG6c9S1UwZjeTanvdY+9OeP05zA+nhzhO1NOLfYAh6+3m18J5ClbcePJP5W+z/cVojVL/Vy14m1+uDNTqwJ3w/oEaeXcIvNSwEqYp3P/jRdReSWc3jRHzdLmBMFkux07nII4Hi8FM2HqGrkgwl0a3UPIicxhfP24N+nv+FmkqG2Q7J7zYpcG+bn/tesd5zB6bKRDQpcnB4KF8f+TXjb7aSk9TicHCh3yCz1pwRdRLDOkEb2jAn3kh/KIs/ZpjjUIAicw4bGOWHY73bJiGMuAyIFimnL1LSSpuNnm3F7mPIHGvtc1W53e8p9kJaKANLeFkEqUxTQj+OfZ3HCviDl+Pg+Xx2RuaCBvTEewRue2Ih/MdMZUttu4PYpSE6xKPEBp2Xb68Rm8+zslXI1qWWG17+u12oLXMZ8nov6XuK2h1PrjNaXtq5sEZCjIxk3jbF84QjM+KA4FjhjUdko6vcbogHobmJ7ffe+gOH4adxD6Wyc1x5VceAG85uKvirhY6hMUN3RuDrmJDmdV3ZW8TSp1+AbfK9vfovglAlZjMN4Nc+AN6IZbjAfBSUgdlpiqmQrKYIctH6NSPdizjG2+LMXdoeKYk5+Al1hie8kHJtNFcXQ73vhIysjaMMGmp7QQCKB5M8ybpBLV89Ku6hm6PRqx+VXX4ajrrurs=
#   app:
#     develop: scrpr-develop
#     master: scrpr-project
# env:
#   global:
#   - secure: Q1qSZ8mtg8QCeJ0A7v5H1N+4kBqnrfRFuMpIP/do8PcqkcFzQ1kj+YPs2mMTfYn1HZeiFC5cYHYXMowjqkPcjpZeVlKOKaHEnFvqp4hUHwX/5O9rxe0tVk3Ye4ap/U8UcohXBtUIt66uq9zF6w82/P3CiAdsuJr73KTjTLTx1Wsr+NbzKGYyCL9l2bQzfXbmgvYAo2gO0WNJwSBc96v23RGEI6k5tPRrPs8R+BrV+rEV6Uhss3KZniRojYEApq7mb/TMOgIXv4fs1oWqABZrmAVfrs5/TGxBlte/Opfqe1dJJd9TmMWbMQkJspoaxb7EEM8FmCcKhyyM8heui7ndSjQE/WfJRL3UKb95/SP2j5vx/VKv/lszSuuapW9Je4DUn9+lXg+yShDxmkjDd5/5vFrGIqRZ3PbAJbI8RYY+AuCVWNKx6M61UIU5Ykgx0xcJE2mHoKW54jYZzJkhGSY5IEQd+14eixUQ7mubI+Y6g9QIwiIYgs8qnhZRjzcmaoraq22YQZafcWz9Sfkg72QKxfWuYd6x/PVjUcaPb6HHL9KtqhIzEsfjEBRXjj0XOkaRTLeEOAoW3ilWqKdKBmQUxL7kxjbKUSKJt+g01rctY5Rk2wAfEvO8g39Nglj6C9o+dwfcbLn5KabQCTEjgDQDUMUBTY79U05K/bHmTr8mmGE=
