os: linux
language: python
python:
- '3.8'
before_install:
- export DJANGO_SETTINGS_MODULE=project.test_settings
install:
- pip install -r requirements.txt
script:
- python manage.py migrate
- python manage.py collectstatic --no-input
- pytest --nomigrations --reuse-db --cov=.
env:
  global:
  - secure: Q1qSZ8mtg8QCeJ0A7v5H1N+4kBqnrfRFuMpIP/do8PcqkcFzQ1kj+YPs2mMTfYn1HZeiFC5cYHYXMowjqkPcjpZeVlKOKaHEnFvqp4hUHwX/5O9rxe0tVk3Ye4ap/U8UcohXBtUIt66uq9zF6w82/P3CiAdsuJr73KTjTLTx1Wsr+NbzKGYyCL9l2bQzfXbmgvYAo2gO0WNJwSBc96v23RGEI6k5tPRrPs8R+BrV+rEV6Uhss3KZniRojYEApq7mb/TMOgIXv4fs1oWqABZrmAVfrs5/TGxBlte/Opfqe1dJJd9TmMWbMQkJspoaxb7EEM8FmCcKhyyM8heui7ndSjQE/WfJRL3UKb95/SP2j5vx/VKv/lszSuuapW9Je4DUn9+lXg+yShDxmkjDd5/5vFrGIqRZ3PbAJbI8RYY+AuCVWNKx6M61UIU5Ykgx0xcJE2mHoKW54jYZzJkhGSY5IEQd+14eixUQ7mubI+Y6g9QIwiIYgs8qnhZRjzcmaoraq22YQZafcWz9Sfkg72QKxfWuYd6x/PVjUcaPb6HHL9KtqhIzEsfjEBRXjj0XOkaRTLeEOAoW3ilWqKdKBmQUxL7kxjbKUSKJt+g01rctY5Rk2wAfEvO8g39Nglj6C9o+dwfcbLn5KabQCTEjgDQDUMUBTY79U05K/bHmTr8mmGE=
  - secure: OAaQmoPrOFb7V9juELM5zxM388KRktDpR5Y/yUjAyqd9CbMKQbOq6upmzhZm8IBDc49N1VfuOAMFm86q2m097o2UW3tWmTrX7e03siP2UxSZLvbgJuaUVoMx5tfAsi96RRN5cX0HqZwA00/rnRC+xYy0y0Xi9EsU06zhi6a1vJ93OkzADbvpzlRc9vW6/qjEZV8URU66XuNXSIz7xrZoGYLzhlglpio/0g/zOoStxdAsjIlKTLvYhQAc/IixLa8gzNv80AIYW1mxijrTlf1zGgDNjWnqiZcF0PQ+QLDBIk2NurwNSos46X0X0/BoXq7STN3TdokP1mswROfHBi1XlJXB86LqvGf7TkqHAr8JoFCxk7SuVgQ+R46MlZWmw2l9tEcj4CwN6Zc6cZrTZtr3rfLc7ctfj8iWNkx9dhhn7GHFhc657ywJG537NA2uKx4elbO+aQW17CCU8wy3v2/hkaxdsbfVRk70ihbOYp81bVUtUQk6NPdrD0gCoVAjJIej0gcTvUFA+UiU4sq9ue8Fg2jJWqg8x6yYXMT97BAnFF7moCPyXmO6xWSBP6F7iCDoDkI7KXEoHtb/ZK8F3oMjnmNAfZKbsUioovDslT09LSnNPuvvLLgj+fTCrrC0bLUE6ov+AwFXZLDxqTd/XibJWMJ16dzFG+CZ1kXYr9Y5MzM=
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: S7rju2g8LOpCG3YMIZhk72SD3j55WZGPRYontZHuWrqG44/okjwKCFTQwNpQyvfDLYxdNwxyRNit+B2GslifwnAqqT87vBBRzMvVkdMm1KsCXZTZGiIkXzimAKztctBvMWMCKJzswSFyhUbEEiQCuHU6Uq5eXZyK4r2ju3c/t+9osAtRoG1Ld7UuZKEUU85lDIKbYKp1JVcKA3uouGAQyHa7MoSiUiH+2gcPw9DzdUK9e8CUo+qWtYgi1+fDh5tLjlMW5Jl2W7rkQkApzytfRI8+V+Tjw9VzmCCnL7zJoWB3Y4y8zqeXLaexa+3yUymNOISugqT9F9FuE6Yja0DPXKIGzsxKa5AxiR0WwYP+TeTq6w02dIUObleek5NK26L2/gSsEuMIRjIfWifWGCT+oOGkhRVJg/8RrSGq2hJHG3WpOFShOAQX4f4xUhYBGJCIXXvQXpUvI0DSXavIjV0b3xqfKmIa14ZiEu64qlodmrW4Cqudgm4xoQyY6QSMfNKZe742zWUc7UdzAtov2pjaKorrCJ7lGLXE4Mp2TRkCYeavJ8mJtv0WFdpZO08bTopktTcH2eG73u952YthctEku9Cwc5dt/iaP4yCopHABue/rxIn+ySN7ntpTeKd21zAV5ITU6GKW5pWBybCskPOb6sleKZAumbHlFDe2fdfiQwE=
  app:
    develop: scrpr-develop
    master: scrpr-project
run:
- export DJANGO_SETTINGS_MODULE=project.settings
- python manage.py collectstatic --no-input
- python manage.py makemigrations
- python manage.py migrate
