# Generated by Django 2.2.6 on 2019-11-23 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('datetime_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('psplus_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('initial_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('employer', models.TextField(blank=True, null=True)),
                ('link', models.URLField(max_length=800)),
                ('source', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', tinymce.models.HTMLField()),
                ('datetime_posted', models.DateTimeField()),
            ],
            options={
                'ordering': ['-datetime_posted'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteJobQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, choices=[(None, 'All Ukraine'), ('Киев', 'Kyiv'), ('Одесса', 'Odessa'), ('Днепр', 'Dnipro'), ('Харьков', 'Kharkov'), ('Львов', 'Lviv')], max_length=50, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('with_salary', models.BooleanField(blank=True, default=False)),
                ('notification_freq', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Never'), (1, 'Every day'), (7, 'Every week'), (30, 'Every month')], null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favorite job queries',
            },
        ),
        migrations.CreateModel(
            name='FavoriteGameQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('psplus_price', models.BooleanField(blank=True, default=False)),
                ('initial_price', models.BooleanField(blank=True, default=False)),
                ('free', models.BooleanField(blank=True, default=False)),
                ('notification_freq', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Never'), (1, 'Every day'), (7, 'Every week'), (30, 'Every month')], null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favorite game queries',
            },
        ),
    ]
