# Generated by Django 3.0.2 on 2020-02-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrpr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
