# Generated by Django 2.2.6 on 2019-11-26 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sharing_with',
            field=models.ManyToManyField(help_text='Account, with whom you want to share your accounting.', related_name='_user_sharing_with_+', related_query_name='sharing_query_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
