# Generated by Django 2.2.6 on 2019-12-14 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_datetime', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('JOB', 'Job'), ('GAME', 'Game')], max_length=10)),
                ('link', models.URLField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', related_query_name='suggestion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
