# Generated by Django 2.2.6 on 2019-12-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsuggestion',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
